### PR TITLE
Rewrite Login

### PR DESCRIPTION
**Pull request by KyleRosenberg**
The login url keeps changing I think, so hopefully this will detect those changes. Also wrote some helper functions to tidy up the login code.

### CODE REVIEW

**Comment by KyleRosenberg** [comment]
Seems like the URL thing was the problem with https://github.com/biw/myCUinfo-API/issues/14

**Review by mguida22 — COMMENTED** [review]
This looks great! Login is working again?

**Comment by KyleRosenberg** [comment]
Login works and classes() works. I think books, info, and gpa are all still broken.

**Review by biw — APPROVED** [review]

**Comment by biw** [comment]
Sorry @KyleRosenberg, just getting to this! Great work, merging in now 😄

**Pull request merged**
